name: MouIcchattaOrder
version: 1.0.0
main: me.MouIcchatta.order.MouIcchattaOrder
api-version: '1.21'
folia-supported: true
author: MouIcchatta

commands:
  order:
    description: Open order menu
    usage: /order
    aliases: [buy, store]

permissions:
  mouicchattaorder.use:
    default: true
  mouicchattaorder.admin:
    default: op
